config/routes.rb
# Rails.application.routes.draw do
#   # Root route, when you visit the homepage
#   root 'pages#home'
  
#   # Routes for signup
#   get '/signup', to: 'users#new'
#   post '/signup', to: 'users#create'

#   # Routes for signin
#   get '/signin', to: 'sessions#new'
#   post '/signin', to: 'sessions#create'
#   delete '/signout', to: 'sessions#destroy' # Correctly set up for signout

#   # Add to playlist action
#   post 'add_to_playlist', to: 'playlists#add_to_playlist'

#   # Routes for albums (only index and show actions)
#   resources :albums do
#     resources :songs
#   end

#   # RESTful routes for playlists
#   resources :playlists do
#     delete 'remove_song/:song_id', to: 'playlists#remove_song', as: 'remove_from_playlist'
#   end
# end
Rails.application.routes.draw do
  get 'playlists/new'
  get 'playlists/create'
  get 'playlists/index'
  get 'playlists/show'
  get 'pages/home'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  # Root route, when you visit the homepage
  root 'pages#home'
  
  # Routes for signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # Routes for signin
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  # delete '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy', as: :signout

  post 'add_to_playlist', to: 'playlists#add_to_playlist'

  # Routes for albums (only index and show actions)
  resources :albums do
    resources :songs
  end

  resources :playlists

  resources :playlists do
    delete 'remove_song/:song_id', to: 'playlists#remove_song', as: 'remove_from_playlist'
  end
  
  
end

app/views/pages/_albums.html.erb
<!-- _albums.html.erb -->
<ul class="space-y-6">
  <% @albums.each do |album| %>
    <li class="bg-darkGray p-3 rounded-lg shadow-lg flex items-center space-x-5 hover:shadow-xl transition-shadow duration-200 mb-6" style="height: 8rem;">
      <%= image_tag album.image.variant(resize_to_fill: [80, 80]).processed, class: "w-20 h-20 object-cover rounded-lg" %>
      <div class="text-green flex-1 ml-4 flex flex-col justify-center">
        <%= link_to album.title, album, class: "text-2xl font-bold hover:underline" %>
        <p class="text-green-light text-sm">
          by <%= album.artist %>, <span class="font-semibold">Release Year: <%= album.release_year %></span>
        </p>
      </div>
      <% if current_user&.admin? %>
        <div class="ml-auto flex flex-col space-y-2">
          
          <%= form_with model: album, method: :delete, local: true, data: { turbo: false } do |form| %>
            <%= form.submit 'Delete', data: { confirm: "Are you sure you want to delete this album?" }, class: "bg-red text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors" %>
          <% end %>

          <%= link_to 'Edit', edit_album_path(album), class: "bg-dark text-white px-4 py-2 rounded-lg hover:bg-gray-800 transition-colors" %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Radio</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="/assets/application.css" media="all" data-turbo-track="reload">
    
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    
  </head>

  <body class="bg-dark h-full text-white font-sans">

    <!-- Navigation Bar -->
    <nav class="bg-darkGray w-full p-4 text-white flex justify-between items-center shadow-lg">
      <div class="text-xl font-semibold">
        <a class="text-white" href="/">Home</a>
      </div>
      <div class="flex items-center">
        <% if current_user %>
          <!-- Create Playlist Button -->
          <%= link_to 'Playlist', playlists_path, class: "bg-green text-white px-3 py-1 rounded mr-2" %>

          <% if current_user.admin? %>
            <!-- Create Album Button for Admins -->
            <%= link_to 'Add Album', new_album_path, class: "bg-green text-white px-3 py-1 rounded mr-2" %>
          <% end %>
        <% end %>

        <!-- Sign Out Link -->
        <%= button_to 'Sign Out', signout_path, method: :delete, class: 'ml-4 text-white', data: { turbo: false } %>
      </div>
    </nav>

    <!-- Albums Section -->
    <div class="container mx-auto p-4 min-h-screen">
      <h1 class="text-3xl font-bold my-4">Albums</h1>
      <div id="albums-list">
        <%= render 'albums' %>
      </div>
    </div>

  </body>
</html>