config/routes.rb
# Rails.application.routes.draw do
#   # Root route, when you visit the homepage
#   root 'pages#home'
  
#   # Routes for signup
#   get '/signup', to: 'users#new'
#   post '/signup', to: 'users#create'

#   # Routes for signin
#   get '/signin', to: 'sessions#new'
#   post '/signin', to: 'sessions#create'
#   delete '/signout', to: 'sessions#destroy' # Correctly set up for signout

#   # Add to playlist action
#   post 'add_to_playlist', to: 'playlists#add_to_playlist'

#   # Routes for albums (only index and show actions)
#   resources :albums do
#     resources :songs
#   end

#   # RESTful routes for playlists
#   resources :playlists do
#     delete 'remove_song/:song_id', to: 'playlists#remove_song', as: 'remove_from_playlist'
#   end
# end
Rails.application.routes.draw do
  get 'playlists/new'
  get 'playlists/create'
  get 'playlists/index'
  get 'playlists/show'
  get 'pages/home'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  # Root route, when you visit the homepage
  root 'pages#home'
  
  # Routes for signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # Routes for signin
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  # delete '/signout', to: 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy', as: :signout

  post 'add_to_playlist', to: 'playlists#add_to_playlist'

  # Routes for albums (only index and show actions)
  resources :albums do
    resources :songs
  end

  resources :playlists

  resources :playlists do
    delete 'remove_song/:song_id', to: 'playlists#remove_song', as: 'remove_from_playlist'
  end
  
  
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :songs
  has_and_belongs_to_many :albums # If you are allowing albums too
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :remove_song]

  def new
    @playlist = Playlist.new
  end

  def create
    # Rails.logger.debug("Received params: #{params.inspect}")
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    # Rails.logger.debug("Playlist Params: #{playlist_params.inspect}")
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @playlist = Playlist.find_by(id: params[:id])
    if @playlist
      @playlist.destroy
      redirect_to playlists_path, notice: 'Playlist was successfully deleted.'
    else
      redirect_to playlists_path, alert: 'Playlist not found.'
    end
  end
  
  def add_to_playlist
    @playlist = Playlist.find(params[:playlist_id])
    @song = Song.find(params[:song_id])
  
    # Here, you'd want to add the song to the playlist
    # This assumes a many-to-many relationship between songs and playlists
    if @playlist.songs << @song
      redirect_to album_path(@song.album), notice: 'Song added to playlist successfully.'
    else
      redirect_to album_path(@song.album), alert: 'Error adding song to playlist.'
    end
  end

  def index
    @playlists = Playlist.all
    @playlist = Playlist.new # Initialize a new Playlist object
  end

  # def remove_song
  #   song = Song.find(params[:song_id])
  #   @playlist.songs.delete(song)  # Remove the song from the playlist

  #   # Redirect back to the playlist's show page
  #   redirect_to @playlist, notice: "Song has been removed from the playlist."
  # end
  # def remove_song
  #   song = Song.find(params[:song_id])
  #   Rails.logger.debug("Playlist ID: #{params[:playlist_id]}")
  #   Rails.logger.debug("Playlist: #{@playlist.inspect}")
  
  #   @playlist.songs.delete(song)  # Remove the song from the playlist
  #   redirect_to @playlist, notice: "Song has been removed from the playlist."
  # end
  # def remove_song
  #   Rails.logger.debug("Playlist: #{@playlist.inspect}")

  #   @playlist = Playlist.find(params[:playlist_id]) # Ensure the playlist is found correctly
  #   song = Song.find(params[:song_id])
  #   @playlist.songs.delete(song)
  
  #   redirect_to @playlist, notice: "Song has been removed from the playlist."
  # end
  def remove_song
    Rails.logger.debug("Parameters: #{params.inspect}")
    
    @playlist = Playlist.find(params[:playlist_id]) 
    Rails.logger.debug("Found Playlist: #{@playlist.inspect}")
  
    song = Song.find(params[:song_id])
    @playlist.songs.delete(song)
  
    redirect_to @playlist, notice: "Song has been removed from the playlist."
  end
  
  
  

  def show
    @songs = @playlist.songs # This should fetch the songs associated with the playlist
  end

  private

  # def set_playlist
  #   Rails.logger.debug("Params: #{params.inspect}") # Log params for debugging
  #   # @playlist = Playlist.find(params[:playlist_id])
  #   @playlist = Playlist.find(params[:id])
  #   # @playlist = Playlist.find(params[:playlist_id]) # Use the correct parameter to find the playlist
  # end 
  def set_playlist
    Rails.logger.debug("Params: #{params.inspect}") # Log params for debugging
    if action_name == 'remove_song'
      @playlist = Playlist.find(params[:playlist_id]) # For remove_song action
    else
      @playlist = Playlist.find(params[:id]) # For show action
    end
  end
  

  def playlist_params
    params.require(:playlist).permit(:name, :description)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/index.html.erb
<div class="min-h-screen flex items-center justify-center bg-dark">
  <div class="bg-darkGray p-4 sm:p-8 sm:rounded-2xl shadow-md w-full max-w-md sm:h-auto flex flex-col justify-start">
    <h2 class="text-green text-2xl font-bold mt-20 mb-10 text-center sm:mt-6 sm:mb-8">Playlists</h2>
    <!-- Display List of Playlists -->
    <ul class="list-disc pl-5 text-white mb-8">
      <% @playlists.each do |playlist| %>
        <li class="flex rounded-2xl bg-dark p-2 justify-between items-center">
          <span>
            <%= link_to playlist.name, playlist_path(playlist), class: "text-green hover:underline" %>
          </span>

          <!-- Delete Playlist Button -->
            <%= button_to "Delete", playlist_path(playlist), method: :delete, class: "ml-4 bg-red text-white p-2 rounded-2xl", data: { confirm: "Are you sure you want to delete this playlist?" } %>
        </li>
      <% end %>
    </ul>

    <!-- Form to Create a New Playlist -->
    <h3 class="text-green text-lg font-semibold mb-2">Create a New Playlist</h3>
    <%= form_with(model: @playlist, local: true, class: "flex flex-col") do |form| %>
    <!-- Playlist Name Input -->
    <div class="mb-4">
        <%= form.text_field :name, placeholder: "Playlist Name", class: "w-full p-3 bg-dark text-white rounded-2xl focus:outline-none focus:ring-2 focus:ring-green" %>
    </div>

    <!-- Submit Button for New Playlist -->
    <div class="mb-4">
        <%= form.submit "Create Playlist", class: "w-full p-3 bg-green text-white rounded-2xl hover:bg-green-dark focus:outline-none" %>
    </div>
    <% end %>
  </div>
</div>

app/views/playlists/new.html.erb
<h1>Playlists#new</h1>
<p>Find me in app/views/playlists/new.html.erb</p>

app/views/playlists/show.html.erb
<div class="min-h-screen flex items-center justify-center bg-dark">
  <div class="bg-darkGray p-4 sm:p-8 sm:rounded-2xl shadow-md w-full max-w-md sm:h-auto flex flex-col justify-start">
    <h1 class="text-green text-3xl font-bold mb-4 text-center">Songs in <%= @playlist.name %></h1>

    <% if @songs.present? %>
      <ul class="list-disc pl-5 text-white mb-8">
        <% @songs.each do |song| %>
          <li class="flex justify-between items-center mb-2">
            <span class="text-white"><%= song.title %></span>

            <!-- Delete Button to remove the song from the playlist -->
            <%= button_to "Delete", playlist_remove_from_playlist_path(@playlist, song_id: song.id), method: :delete, class: "bg-red text-white p-2 rounded hover:bg-red-dark", data: { confirm: "Are you sure you want to remove this song from the playlist?" } %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-white">No songs found in this playlist.</p>
    <% end %>

    <div class="mt-4">
      <%= link_to 'Back to Playlists', playlists_path, class: "text-green hover:underline" %>
    </div>
  </div>
</div>